// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-4qGLHFrUbnaqPWkBpiU_ifQ80MkQbv0',
    appId: '1:958105833380:web:0b91b46aac61c7f3973b31',
    messagingSenderId: '958105833380',
    projectId: 'linkedinclone-63399',
    authDomain: 'linkedinclone-63399.firebaseapp.com',
    storageBucket: 'linkedinclone-63399.appspot.com',
    measurementId: 'G-RRYE1B52W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABYnxBEnH2IaN15qtQiIPymoRdbE8FT50',
    appId: '1:958105833380:android:58b54e16a5d760fc973b31',
    messagingSenderId: '958105833380',
    projectId: 'linkedinclone-63399',
    storageBucket: 'linkedinclone-63399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpYjt3SCwzsOMhxRwuEbEtc9As0h8sjI',
    appId: '1:958105833380:ios:9978a523a55ff02a973b31',
    messagingSenderId: '958105833380',
    projectId: 'linkedinclone-63399',
    storageBucket: 'linkedinclone-63399.appspot.com',
    iosClientId: '958105833380-kn0dk0arvgin00qb8l2sjnpkmropfdse.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkedinclone',
  );
}
